### PR TITLE
SDK enhancements

### LINKED ISSUE #9: Fatal error: Public Key / Authentication Endpoint is not defined while initalizing the SDK
**Describe the bug**
Got Fatal Error: 
ImageKitIO/ImageKitUploader.swift:55: Fatal error: Public Key / Authentication Endpoint is not defined while initalizing the SDK

**To Reproduce**

**Expected behavior**
Upload image without error

**Code**
`
import SwiftUI
import ImageKitIO
@main struct ImageKitIO_TestApp: App {
    init(){
        initImageKitIO()
    }
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
    
    func initImageKitIO(){
        _ = ImageKit.init(
            publicKey: "MYPUBLIC_KEY=",
            urlEndpoint: "https://ik.imagekit.io/NAME",
            transformationPosition: TransformationPosition.PATH
        )
    }
}

struct ContentView: View {
    
    @State var status: String? = nil
    
    var body: some View {
        Button {
            upload()
        } label: {
            Text("Upload")
        }
        
        if let t = status {
            Text(t)
                .font(.largeTitle)
                .foregroundColor(.red)
        }
    }
    
    func upload() {
        guard let image = UIImage(named: "avatar") else {
            print("can't create image")
            return
        }
        
        ImageKit.shared.uploader().upload(
          file: image,
          fileName: "sample-image.jpg",
          useUniqueFilename: true,
          tags: ["demo"],
          folder: "/",
          isPrivateFile: false,
          customCoordinates: "",
          responseFields: "",
          signatureHeaders: ["x-test-header":"Test"],
          progress: { progress in
              // Handle Progress
          },
          completion: { result in
               switch result {
                    case .success(let uploadAPIResponse):
                        // Handle Success Response
                        print(uploadAPIResponse)
                        status = "success"
                    case .failure(let error as UploadAPIError):
                        // Handle Upload Error
                        status = error.localizedDescription
                    case .failure(let error):
                        // Handle Other Errors
                        status = error.localizedDescription
              }
          }
        )
    }
}

`

**Desktop (please complete the following information):**
 - Xcode 13.2

**Smartphone (please complete the following information):**
 - iOS 15.2

### PR DESCRIPTION
**Pull request by AniVerma17**
- Add following features in the SDK:
  - URL constructor methods for adaptive video streaming, adding raw transform options as a string, and image loading in the responsive manner according to the target view.
  - Upload policy to set constraints on upload requests for device conditions, retry mechanism etc.
  - Upload preprocessors to transform images and video before uploading.
- Migrate the uploader methods and API calls to the V2 upload API.
- Remove the deprecated overlay transformation options from URL constructor.

Also resolves #9.

### CODE REVIEW

File: ImageKit/ImageKitUploader.swift [hunk 1]
```diff
@@ -6,88 +6,218 @@
 //
 
 import Foundation
+import Network
+//import Reachability
```
Comment (ahnv) [inline ImageKit/ImageKitUploader.swift:10]: remove

File: ImageKit/Util/UploadApi.swift [hunk 2]
```diff
@@ -8,67 +8,154 @@
...
+                        isPrivateFile: isPrivateFile,
+                        progressClosure: progressClosure,
+                        urlConfiguration: urlConfiguration,
+                        uploadPolicy: uploadPolicy,
+                        completion: completion,
+                        retryCount: retryCount + 1
+                    )
                 }
-                completion(Result.success((response, try? IKJSONDecoder().decode(UploadAPIResponse.self, from: data!))))
             }
```
Comment (ahnv) [inline ImageKit/Util/UploadApi.swift:148]: Should we add a log line here that this was the error, retrying.

Also, we should have a handling here that if the error is retryable or not, if the response code is 403, that means the token is invalid, no point sending the same request again

File: ImageKit/ImageKit.swift [hunk 3]
```diff
@@ -6,27 +6,27 @@
 //
 
 import Foundation
-public let API_VERSION: String = Bundle(identifier: "org.cocoapods.ImageKitIO")?.infoDictionary!["CFBundleShortVersionString"] as? String ?? "Unknown"
```
Comment (ahnv) [inline ImageKit/ImageKit.swift:9]: we have completely dropped API_VERSION from the generated url, @manu4543 should we have a flag where it is conditionally set? like by default it is added but you can configure it to be off

**Review by ahnv — CHANGES_REQUESTED** [review]

File: ImageKit/ImageKit.swift (hunk 3 above)
Comment (imagekitio) [reply ImageKit/ImageKit.swift:9]: it should never be set now we dropped it in all places. IIRC, we removed it in android too @AniVerma17

File: ImageKit/Util/UploadApi.swift (hunk 2 above)
Comment (AniVerma17) [reply ImageKit/Util/UploadApi.swift:148]: @ahnv this block is for performing the retries in case of errors like timeouts, network errors etc. Handling of errors from HTTP responses is being handled from line 108, where the check for HTTP 4xx responses is present.
I'll add the log statements for error here and everywhere else in this function.

File: ImageKit/ImageKit.swift (hunk 3 above)
Comment (AniVerma17) [reply ImageKit/ImageKit.swift:9]: > it should never be set now we dropped it in all places. IIRC, we removed it in android too @AniVerma17

Yes, this parameter was completely removed with no option to toggle by the consumer app.

File: ImageKit/ImageKitUploader.swift (hunk 1 above)
Comment (AniVerma17) [reply ImageKit/ImageKitUploader.swift]: Done

File: Example/ImageKit/FetchImageViewController.swift [hunk 4]
```diff
@@ -39,28 +39,22 @@ class FetchImageViewController: UIViewController {
...
     
     @IBAction func OnClickTransformation3(_ sender: Any) {
-        let url = ImageKit.shared.url(src: "https://ik.imagekit.io/demo/medium_cafe_B1iTdD0C.jpg", transformationPosition: TransformationPosition.PATH)
-            .overlayImage(overlayImage: "logo-white_SJwqB4Nfe.png")
-            .overlayX(overlayX: 10)
-            .overlayY(overlayY: 20)
-            .create()
+        guard let url = try? ImageKit.shared.url(src: "https://ik.imagekit.io/demo/medium_cafe_B1iTdD0C.jpg", transformationPosition: TransformationPosition.PATH)
+            .setResponsive(view: imageView)
+            .create() else { return }
```
Comment (ahnv) [inline Example/ImageKit/FetchImageViewController.swift:44]: This should include the overlay in this example, using layer syntax as it was originally

output url should be
https://ik.imagekit.io/demo/tr:l-image,i-logo-white_SJwqB4Nfe.png,ox-10,l-end/medium_cafe_B1iTdD0C.jpg

File: Example/ImageKit/FetchImageViewController.swift [hunk 5]
```diff
@@ -39,28 +39,22 @@ class FetchImageViewController: UIViewController {
...
         self.showImage(url: url)
     }
     
     @IBAction func OnClickTransformation4(_ sender: Any) {
         let url = ImageKit.shared.url(src: "https://ik.imagekit.io/demo/tr:oi-logo-white_SJwqB4Nfe.png,ox-N10,oy-20/medium_cafe_B1iTdD0C.jpg")
+            .raw(params: "l-text,i-ik_logo.png,lx-20,ly-20,r-32,l-end")
             .create()
```
Comment (ahnv) [inline Example/ImageKit/FetchImageViewController.swift:51]: Please use the same transformation for example as the original
```
https://ik.imagekit.io/demo/tr:l-image,i-logo-white_SJwqB4Nfe.png,lx-N20,ly-20,l-end/medium_cafe_B1iTdD0C.jpg
```

this should be the url

File: Example/ImageKit/FetchImageViewController.swift [hunk 6]
```diff
@@ -39,28 +39,22 @@ class FetchImageViewController: UIViewController {
...
         self.showImage(url: url)
     }
     
     @IBAction func OnClickTransformation5(_ sender: Any) {
         let url = ImageKit.shared.url(src: "https://ik.imagekit.io/demo/img/plant.jpeg?tr=oi-logo-white_SJwqB4Nfe.png,ox-10,oy-20")
             .addCustomTransformation(key: "w", value: "400")
```
Comment (ahnv) [inline Example/ImageKit/FetchImageViewController.swift:57]: The url output should be `https://ik.imagekit.io/demo/img/plant.jpeg?tr=w-400:l-text,i-Hand%20with%20a%20green%20plant,co-264120,fs-30,lx-10,ly-20,l-end`

File: Tests/Tests.swift [hunk 7]
```diff
@@ -1115,14 +590,64 @@ class UnitTestSpec: QuickSpec {
...
-                expect(actual).to(equal(String(format: "https://ik.imagekit.io/demo/medium_cafe_B1iTdD0C.jpg?ik-sdk-version=ios-%@&tr=h-300,w-300:rt-90", apiVersion)))
+                expect(actual).to(equal(String(format: "https://ik.imagekit.io/demo/medium_cafe_B1iTdD0C.jpg?tr=h-300,w-300:rt-90")))
+            }
+            it("With raw transforms string") {
+                let actual = ImageKit.shared
+                    .url(src: "https://ik.imagekit.io/demo/medium_cafe_B1iTdD0C.jpg")
+                    .raw(params: "h-300,w-300,rt-90")
+                    .create()
+                expect(actual).to(equal(String(format: "https://ik.imagekit.io/demo/medium_cafe_B1iTdD0C.jpg?tr=h-300,w-300,rt-90")))
             }
```
Comment (ahnv) [inline Tests/Tests.swift:601]: add test for raw that includes the layer syntax

https://ik.imagekit.io/demo/img/plant.jpeg?tr=w-400:l-text,i-Hand%20with%20a%20green%20plant,co-264120,fs-30,lx-10,ly-20,l-end

you can use this one

**Review by ahnv — CHANGES_REQUESTED** [review]

File: ImageKit/ImageKitUploader.swift [hunk 8]
```diff
@@ -6,88 +6,217 @@
...
-        customCoordinates: String? = "",
-        responseFields: String? = "",
-        signatureHeaders: [String: String]? = [String: String](),
+        useUniqueFilename: Bool? = nil,
+        tags: [String]? = nil,
+        folder: String? = nil,
+        isPrivateFile: Bool? = nil,
+        customCoordinates: String? = nil,
+        responseFields: String? = nil,
+        extensions: [[String : Any]]? = nil,
```
Comment (ahnv) [inline ImageKit/ImageKitUploader.swift:120]: Is it possible for us to have a proper type for extensions rather than `[["string": Any]]`

Comment (AniVerma17) [reply ImageKit/ImageKitUploader.swift:120]: @ahnv the extensions here are basically JSON objects whose schema can vary across different extensions, so it is not feasible to define a concrete type for all the extensions. the type `[String : Any]` correctly maps from and to a variable JSON structure.

File: Example/ImageKit/FetchImageViewController.swift (hunk 4 above)
Comment (AniVerma17) [reply Example/ImageKit/FetchImageViewController.swift]: Done

File: Example/ImageKit/FetchImageViewController.swift (hunk 5 above)
Comment (AniVerma17) [reply Example/ImageKit/FetchImageViewController.swift]: Done

File: Example/ImageKit/FetchImageViewController.swift (hunk 6 above)
Comment (AniVerma17) [reply Example/ImageKit/FetchImageViewController.swift]: Done

File: Tests/Tests.swift (hunk 7 above)
Comment (AniVerma17) [reply Tests/Tests.swift]: Done

**Comment by wtsnz** [comment]
Hey, I've been using the latest version and have noticed the the ability to subscribe to progress updates via the `uploadProgressHandler` doesn't work. Progress is never reported on media uploads. I was curious if this is 1) a known issue, and 2) if so, planned to be fixed.

**Comment by imagekitio** [comment]
@ahnv are we okay in using v2 version of upload API?

**Comment by ahnv** [comment]
> @ahnv are we okay in using v2 version of upload API?

I have added the v2 dummy server, we should be good to provide the functionality

File: Example/ImageKit/AppDelegate.swift [hunk 9]
```diff
@@ -15,7 +15,7 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
     var window: UIWindow?
 
     func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
-        _ = ImageKit.init(publicKey: "your_public_key", imageKitEndpoint: "https://ik.imagekit.io/your_imagekit_id", transformationPosition: TransformationPosition.PATH, authenticationEndpoint: "http://localhost:8080/auth")
+        ImageKit.init(publicKey: "IK_PUBLIC_KEY", urlEndpoint: "https://ik.imagekit.io/IK_ID", transformationPosition: TransformationPosition.PATH)
```
Comment (ahnv) [inline Example/ImageKit/AppDelegate.swift:18]: Please move the `IK_PUBLIC_KEY` and `https://ik.imagekit.io/IK_ID` to a constants file like done in android

File: Example/ImageKit/UploadAuthService.swift [hunk 10]
```diff
@@ -0,0 +1,48 @@
...
+class UploadAuthService {
+    static let dispatchGroup = DispatchGroup()
+    
+    static func getUploadToken(payload: [String : String]) -> [String : String]? {
+        let urlSession = URLSession(configuration: URLSessionConfiguration.default, delegate: URLSession.shared.delegate, delegateQueue: URLSession.shared.delegateQueue)
+        var request = URLRequest(url: URL(string: "AUTH_SERVER_HOST")!)
+        request.httpMethod = "POST"
+        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
+        var tokenResponse: [String : String]? = nil
+        guard let body = try? JSONSerialization.data(withJSONObject: ["uploadPayload": payload, "expire": 60, "publicKey": "IK_PUBLIC_KEY"] as [String : Any]) else {
```
Comment (ahnv) [inline Example/ImageKit/UploadAuthService.swift:20]: `IK_PUBLIC_KEY` should come from a constants file

File: Example/ImageKit/AppDelegate.swift (hunk 9 above)
Comment (ahnv) [reply Example/ImageKit/AppDelegate.swift:18]: The constants file should look like this https://github.com/imagekit-samples/quickstart/pull/40/commits/75d79da378538eaa1ae8d9e1169b53e76c2514a5

File: Example/ImageKit/UploadAuthService.swift (hunk 10 above)
Comment (AniVerma17) [reply Example/ImageKit/UploadAuthService.swift:20]: Done

Comment (ahnv) [reply Example/ImageKit/UploadAuthService.swift:20]: This one value is still left, should come from constants

Comment (AniVerma17) [reply Example/ImageKit/UploadAuthService.swift]: Done

**Review by ahnv — APPROVED** [review]
