### PR TITLE
Swift package support

### LINKED ISSUE #10: Is this SDK available via Swift Package Manager?
**Describe the bug**
I am unable to install the ImageKit iOS SDK via the Swift Package Manager in XCode.

**To Reproduce**
Plug https://github.com/imagekit-developer/imagekit-ios/ into "Add Packages" via XCode. Received the error message "Package Resolution Failed."

**Expected behavior**
The package should resolve successfully.

**Screenshots**
Screen Shot 2022-03-25 at 5 07 13 PM

### PR DESCRIPTION
**Pull request by AniVerma17**
Resolve #10 and #28
- Add Swift package configuration to the library to be available via SPM (Swift Package Manager)
- Refactor library code to be compatible with the Swift 6 concurrency standards
- Bump the minimum deployment target to iOS 13.0

### CODE REVIEW

File: Sources/ImageKit/ImageKit.swift [hunk 1]
```diff
@@ -24,9 +23,10 @@ open class ImageKit: NSObject {
     var configured = false
     lazy var userDefaults = UserDefaults.standard
 
-    public static let shared = ImageKit()
+    nonisolated(unsafe) public static let shared = ImageKit()
```
Comment (ahnv) [inline Sources/ImageKit/ImageKit.swift]: Could we consider refactoring this to avoid using `nonisolated(unsafe)`?
It’s generally meant as a temporary workaround and not recommended for long-term use. 
To stay aligned with Swift’s concurrency standards, we should prefer proper actor isolation or a thread-safe synchronization approach.

If we need to keep `nonisolated(unsafe)` for now, let’s ensure that all access is explicitly guarded by an external synchronization mechanism (e.g., a lock or dispatch queue), as suggested in the Swift documentation:

> “Only use nonisolated(unsafe) when you are carefully guarding all access to the variable with an external synchronization mechanism such as a lock or dispatch queue.”

File: Sources/ImageKit/Util/UploadApi.swift
Comment (ahnv) [inline Sources/ImageKit/Util/UploadApi.swift:33]: Can we use proper typed models for extensions instead of passing `[ [String: Any] ]` directly?

This will make the API safer and improve developer experience (DX), similar to how other SDKs handle it. For example, we could define a type-safe wrapper using ExtensionType enums with associated models and a small helper for serialization:

```
typealias Extensions = [ExtensionType]

enum ExtensionType: Codable {
    case removeBg(RemoveBg)
    case autoTagging(AutoTaggingExtension)
    case aiAutoDescription(AIAutoDescription)
    // ...
}

private extension Encodable {
    func asDictionary() throws -> [String: Any] {
        let data = try JSONEncoder().encode(self)
        return try JSONSerialization.jsonObject(with: data) as? [String: Any] ?? [:]
    }
}

func upload(
  /* same params... */,
  extensions: [ExtensionType]?,
  /* ... */
) {
    let extDicts = try? extensions?.map {
        switch $0 {
        case .removeBg(let v):          return try v.asDictionary()
        case .autoTagging(let v):       return try v.asDictionary()
        case .aiAutoDescription(let v): return try v.asDictionary()
        }
    }

    // forward to the existing implementation
    upload(/* ... */, extensions: extDicts, /* ... */)
}
```

Refer to [nodejs SDK](https://github.com/imagekit-developer/imagekit-nodejs/blob/cd9bc302f9abfea876c356930193638443b42eb1/src/resources/files/files.ts#L1305) for the types structure

File: Sources/ImageKit/Util/UploadApi.swift [hunk 2]
```diff
@@ -8,12 +8,20 @@
...
+    init(value: Any) {
+        self.value = value
+    }
+}
+
+class UploadAPI: NSObject, URLSessionTaskDelegate, @unchecked Sendable {
+    nonisolated(unsafe) internal static var baseUrl = "https://upload.imagekit.io"
     internal static let log = OSLog(subsystem: Bundle.main.bundleIdentifier!, category: "ImageKitIO")
     
     internal static func upload(
```
Comment (ahnv) [inline Sources/ImageKit/Util/UploadApi.swift:23]: We should expose the `transformation`, `checks`, and `isPublished` parameters as part of the upload API so that developers can take advantage of all available upload options defined in the ImageKit documentation.

Comment (ahnv) [reply Sources/ImageKit/Util/UploadApi.swift:23]: When exposing the transformation parameter, we should follow the same approach used for extensions (as mentioned in the comment here: https://github.com/imagekit-developer/imagekit-ios/pull/29/files#r2454809821)

File: Sources/ImageKit/Util/UploadApi.swift [hunk 3]
```diff
@@ -8,12 +8,20 @@
...
 
-class UploadAPI: NSObject, URLSessionTaskDelegate {
-    internal static var baseUrl = "https://upload.imagekit.io"
+fileprivate class SendableAny : @unchecked Sendable {
+    let value: Any
+    
+    init(value: Any) {
+        self.value = value
+    }
+}
```
Comment (ahnv) [inline Sources/ImageKit/Util/UploadApi.swift:17]: By doing [properly typed parameters](https://github.com/imagekit-developer/imagekit-ios/pull/29/files#r2454809821) can we eliminate the use of SendableAny?

File: Sources/ImageKit/ImageKit.swift [hunk 4]
```diff
@@ -24,9 +23,10 @@ open class ImageKit: NSObject {
...
     
-    private let sharedUploader = ImageKitUploader()
+    @MainActor
+    private lazy var sharedUploader = ImageKitUploader()
```
Comment (ahnv) [inline Sources/ImageKit/ImageKit.swift:29]: Are we sure we should run the uploader on the main thread?
AFAIK, MainActor should be used on UI-bound work. Network I/O and any heavy pre-processing (resizing, JPEG/HEIC encoding) should run off the main actor to avoid jank.

There are some concerns related to the concurrency which GPT and Claude have raised and I agree with them, we should look into those very carefully

File: ImageKitIO.podspec [hunk 5]
```diff
@@ -1,6 +1,6 @@
 Pod::Spec.new do |s|
   s.name             = 'ImageKitIO'
-  s.version          = '3.0.0'
+  s.version          = '3.1.0'
```
Comment (ahnv) [inline ImageKitIO.podspec:3]: We should bump this to v4 and provide a changelog / migration guide to cover the following
- Breaking changes from v3.0
- Swift 6 concurrency requirements
- Code examples for common migrations

File: README.md [hunk 6]
```diff
@@ -13,7 +13,34 @@ ImageKit iOS Pod allows you to use real-time [image resizing](https://docs.image
 ## Installation
 
 ### Requirements
-The library requires Swift 4.0 or above.
+The library requires Swift 6.0 or above.
```
Comment (ahnv) [inline README.md]: We should mention minimum iOS version also in this line

File: README.md [hunk 7]
```diff
@@ -13,7 +13,34 @@ ImageKit iOS Pod allows you to use real-time [image resizing](https://docs.image
...
+            name: "Example",
+            ...
+            dependencies: [
+                "ImageKitIO",
+                ...
+            ],
+        ),
+    ]
+)
+```
```
Comment (ahnv) [inline README.md]: We will need to update the Readme to be properly documented

#### Swift Package Manager

You can integrate ImageKit into your iOS project using the Swift Package Manager (SPM).

After completing the Swift Package setup in your project, you can add ImageKit in one of the following ways:

**Using Xcode**

Open your project in Xcode, then go to File → Add Packages….
In the search bar, enter the ImageKit package repository URL:
```
https://github.com/imagekit-developer/imagekit-ios.git
```
Select the Up to Next Major version rule, starting from version 3.1.0, and add the package to your app target’s Package Dependencies list.

**Using `Package.swift`**
If you prefer managing dependencies manually, add ImageKit to the dependencies array in your `Package.swift` file:

```
// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Example",
    platforms: [
        .iOS(.v13)
    ],
    dependencies: [
        .package(url: "https://github.com/imagekit-developer/imagekit-ios.git", .upToNextMajor(from: "3.1.0"))
    ],
    targets: [
        .target(
            name: "Example",
            dependencies: [
                "ImageKitIO"
            ]
        )
    ]
)
```


Once added, you can import ImageKitIO into your Swift files:

```
import ImageKitIO
```

**Review by ahnv — CHANGES_REQUESTED** [review]

File: Sources/ImageKit/ImageKit.swift (hunk 4 above)
Comment (AniVerma17) [reply Sources/ImageKit/ImageKit.swift:29]: @ahnv if you look into the implementation of the upload functions in the _ImageKitUploader_ class, all the media preprocessing and upload API calls are executed on background threads via GCD. So it is safe to call these methods on the main actor, since they internally offload the heavy tasks away from it.

File: Sources/ImageKit/Util/UploadApi.swift (hunk 2 above)
Comment (AniVerma17) [reply Sources/ImageKit/Util/UploadApi.swift:23]: @ahnv I suggest we defer this to a separate minor release after this one is merged.
Not only this change is unrelated to the SPM support, but also we'll need to implement the same changes in the Android SDK as well to maintain feature parity. Segregating this task into another release will ease the simultaneous updates in both the SDKs for these changes.

File: README.md (hunk 7 above)
Comment (AniVerma17) [reply README.md]: Done

File: README.md (hunk 6 above)
Comment (AniVerma17) [reply README.md]: Done

File: Sources/ImageKit/ImageKit.swift (hunk 1 above)
Comment (AniVerma17) [reply Sources/ImageKit/ImageKit.swift]: @ahnv fixed this by refactoring the _ImageKit_ class to conform to _Sendable_ protocol, subsequently removing the _nonisolated_ modifier from the shared object

File: Sources/ImageKit/Util/UploadApi.swift
Comment (AniVerma17) [reply Sources/ImageKit/Util/UploadApi.swift:33]: @ahnv just to be sure, are the possible values of upload extensions constrained to aforementioned types only, or the SDK users can create and pass custom extensions to the upload API?
The current implementation was written keeping the latter case in mind. However, if the extensions' schema is constrained, then we can define these as concrete types.

File: Sources/ImageKit/Util/UploadApi.swift (hunk 3 above)
Comment (AniVerma17) [reply Sources/ImageKit/Util/UploadApi.swift:17]: @ahnv while we can eliminate the use for upload extensions by this method, we cannot do the same for the _customMetadata_ dictionary, which can have the values of varying types. So we still need the _SendableAny_ type to handle that case.

File: Sources/ImageKit/Util/UploadApi.swift
Comment (ahnv) [reply Sources/ImageKit/Util/UploadApi.swift:33]: Yes the extensions schema has been static for a while, we can send an update when it get's updated later

File: Sources/ImageKit/Util/UploadApi.swift (hunk 2 above)
Comment (ahnv) [reply Sources/ImageKit/Util/UploadApi.swift:23]: That works, Let's do it as part of next release

File: Sources/ImageKit/Util/UploadApi.swift
Comment (ahnv) [reply Sources/ImageKit/Util/UploadApi.swift:33]: Let's cover this as part of next release

File: Sources/ImageKit/Util/UploadApi.swift (hunk 3 above)
Comment (ahnv) [reply Sources/ImageKit/Util/UploadApi.swift:17]: Let's cover this as part of next release with proper typings

File: Sources/ImageKit/ImageKit.swift (hunk 4 above)
Comment (ahnv) [reply Sources/ImageKit/ImageKit.swift:29]: Understood

File: ImageKitIO.podspec (hunk 5 above)
Comment (AniVerma17) [reply ImageKitIO.podspec:3]: @ahnv there are no breaking changes in this release. We're maintaining the older Cocoapods spec with the SPM config, and the API surface is also the same. So bumping the major version doesn't make sense for this one.
